name: food_assistant
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0

  # Voice Tool
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.5
  
  # Formatting
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # App Icon Generator
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Add this to tell Flutter to pack all your images!
  assets:
    - assets/

# App Icon Configuration
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21